{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error checking website URL: Invalid URL 'URL': No schema supplied. Perhaps you meant http://URL?\n",
      "Error checking website https://chat.topsearcher.top/: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))\n",
      "Error checking website https://www.aicodehelper.com/: HTTPSConnectionPool(host='www.aicodehelper.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028704D385B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Error checking website https://geekch.art/: HTTPSConnectionPool(host='geekch.art', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040DCF10>, 'Connection to geekch.art timed out. (connect timeout=10)'))Error checking website https://poe.com/: HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040DEF80>, 'Connection to poe.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://chat8.yqcloud.top/: HTTPSConnectionPool(host='chat8.yqcloud.top', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B6DEA0>, 'Connection to chat8.yqcloud.top timed out. (connect timeout=10)'))\n",
      "\n",
      "Error checking website https://wen.geekr.dev: HTTPSConnectionPool(host='wen.geekr.dev', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B6E290>, 'Connection to wen.geekr.dev timed out. (connect timeout=10)'))\n",
      "Error checking website https://chatbot.theb.ai/: HTTPSConnectionPool(host='chatbot.theb.ai', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040DE470>, 'Connection to chatbot.theb.ai timed out. (connect timeout=10)'))\n",
      "Error checking website https://free.anzz.top/: HTTPSConnectionPool(host='free.anzz.top', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B6C3D0>, 'Connection to free.anzz.top timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.askme.mom/: HTTPSConnectionPool(host='www.askme.mom', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B8BE20>, 'Connection to www.askme.mom timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.aiai.zone: HTTPSConnectionPool(host='www.aiai.zone', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B8AF20>, 'Connection to www.aiai.zone timed out. (connect timeout=10)'))\n",
      "Error checking website https://chat8.xeasy.me: HTTPSConnectionPool(host='chat8.xeasy.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B8BF10>, 'Connection to chat8.xeasy.me timed out. (connect timeout=10)'))\n",
      "Error checking website https://desk.im/: HTTPSConnectionPool(host='desk.im', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040B62F0>, 'Connection to desk.im timed out. (connect timeout=10)'))\n",
      "Error checking website https://ai.ls/: HTTPSConnectionPool(host='ai.ls', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B894B0>, 'Connection to ai.ls timed out. (connect timeout=10)'))\n",
      "Error checking website https://freegpt.one/: HTTPSConnectionPool(host='freegpt.one', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040B5C90>, 'Connection to freegpt.one timed out. (connect timeout=10)'))\n",
      "Error checking website https://aka.mydog.buzz: HTTPSConnectionPool(host='aka.mydog.buzz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040B6B90>, 'Connection to aka.mydog.buzz timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.teach-anything.com/: HTTPSConnectionPool(host='www.teach-anything.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040B6CE0>, 'Connection to www.teach-anything.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://gpt.getshare.net/: HTTPSConnectionPool(host='gpt.getshare.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704054AF0>, 'Connection to gpt.getshare.net timed out. (connect timeout=10)'))\n",
      "Error checking website https://ai.ci: HTTPSConnectionPool(host='ai.ci', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028703FC4C70>, 'Connection to ai.ci timed out. (connect timeout=10)'))\n",
      "Error checking website https://beta.character.ai/: HTTPSConnectionPool(host='beta.character.ai', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028703B9D2A0>, 'Connection to beta.character.ai timed out. (connect timeout=10)'))\n",
      "Error checking website http://ai.jjzn.top/: HTTPConnectionPool(host='ai.jjzn.top', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000287040C5510>, 'Connection to ai.jjzn.top timed out. (connect timeout=10)'))Error checking website https://xc.com/: HTTPSConnectionPool(host='xc.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704046D70>, 'Connection to xc.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://openprompt.co/ChatGPT: HTTPSConnectionPool(host='openprompt.co', port=443): Max retries exceeded with url: /ChatGPT (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040C4EB0>, 'Connection to openprompt.co timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.ftcl.store/: HTTPSConnectionPool(host='www.ftcl.store', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040C4C70>, 'Connection to www.ftcl.store timed out. (connect timeout=10)'))\n",
      "Error checking website https://chat5.xeasy.me/: HTTPSConnectionPool(host='chat5.xeasy.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040C48B0>, 'Connection to chat5.xeasy.me timed out. (connect timeout=10)'))\n",
      "\n",
      "Error checking website https://94gpt.com/: HTTPSConnectionPool(host='94gpt.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040C6BC0>, 'Connection to 94gpt.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.ohmygpt.com/: HTTPSConnectionPool(host='www.ohmygpt.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704DEC580>, 'Connection to www.ohmygpt.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://tryai.top/freechat: HTTPSConnectionPool(host='tryai.top', port=443): Max retries exceeded with url: /freechat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704DEDB10>, 'Connection to tryai.top timed out. (connect timeout=10)'))\n",
      "Error checking website https://chatcat.pages.dev/: HTTPSConnectionPool(host='chatcat.pages.dev', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704DEC100>, 'Connection to chatcat.pages.dev timed out. (connect timeout=10)'))\n",
      "Error checking website https://chatmindai.com/: HTTPSConnectionPool(host='chatmindai.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704DECF40>, 'Connection to chatmindai.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.typingmind.com/: HTTPSConnectionPool(host='www.typingmind.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704E2AAD0>, 'Connection to www.typingmind.com timed out. (connect timeout=10)'))\n",
      "Error checking website http://newb.site/chatgpt: HTTPConnectionPool(host='newb.site', port=80): Max retries exceeded with url: /chatgpt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000028704DEDA20>, 'Connection to newb.site timed out. (connect timeout=10)'))\n",
      "Error checking website https://gpt.clashus.com/: HTTPSConnectionPool(host='gpt.clashus.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704E2BAC0>, 'Connection to gpt.clashus.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://ai117.com/: HTTPSConnectionPool(host='ai117.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704DCF2B0>, 'Connection to ai117.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://ai.okmiku.com/chat/: HTTPSConnectionPool(host='ai.okmiku.com', port=443): Max retries exceeded with url: /chat/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CDD6C0>, 'Connection to ai.okmiku.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://chat.51buygpt.com/: HTTPSConnectionPool(host='chat.51buygpt.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CDDCC0>, 'Connection to chat.51buygpt.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://litechat.22733.site/: HTTPSConnectionPool(host='litechat.22733.site', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CDDC90>, 'Connection to litechat.22733.site timed out. (connect timeout=10)'))\n",
      "Error checking website https://chat.sunls.me/: HTTPSConnectionPool(host='chat.sunls.me', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CDEA10>, 'Connection to chat.sunls.me timed out. (connect timeout=10)'))\n",
      "Error checking website https://chat35.com/: HTTPSConnectionPool(host='chat35.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CEFEE0>, 'Connection to chat35.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://freechatgpt.chat/: HTTPSConnectionPool(host='freechatgpt.chat', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CEEA40>, 'Connection to freechatgpt.chat timed out. (connect timeout=10)'))\n",
      "Error checking website https://chatforai.com/: HTTPSConnectionPool(host='chatforai.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CEE050>, 'Connection to chatforai.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://trychatgp.com/: HTTPSConnectionPool(host='trychatgp.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CEF610>, 'Connection to trychatgp.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.abab123.tk/: HTTPSConnectionPool(host='www.abab123.tk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D39E40>, 'Connection to www.abab123.tk timed out. (connect timeout=10)'))\n",
      "Error checking website https://wordstory.streamlit.app/: HTTPSConnectionPool(host='wordstory.streamlit.app', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D39270>, 'Connection to wordstory.streamlit.app timed out. (connect timeout=10)'))\n",
      "Error checking website https://chatplus.app: HTTPSConnectionPool(host='chatplus.app', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D540A0>, 'Connection to chatplus.app timed out. (connect timeout=10)'))\n",
      "Error checking website https://docsgpt.arc53.com/: HTTPSConnectionPool(host='docsgpt.arc53.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D38400>, 'Connection to docsgpt.arc53.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://zhoubaotong.com/zh: HTTPSConnectionPool(host='zhoubaotong.com', port=443): Max retries exceeded with url: /zh (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D55DE0>, 'Connection to zhoubaotong.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://hotoke.ai/: HTTPSConnectionPool(host='hotoke.ai', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D39930>, 'Connection to hotoke.ai timed out. (connect timeout=10)'))\n",
      "Error checking website https://chilloutai.com/: HTTPSConnectionPool(host='chilloutai.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D39C60>, 'Connection to chilloutai.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://vrtalk.io/: HTTPSConnectionPool(host='vrtalk.io', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D63B50>, 'Connection to vrtalk.io timed out. (connect timeout=10)'))\n",
      "Error checking website https://builtbyjesse.com/lab: HTTPSConnectionPool(host='builtbyjesse.com', port=443): Read timed out. (read timeout=10)\n",
      "Error checking website https://openai.onenov.cn/: HTTPSConnectionPool(host='gpt.orence.net', port=443): Max retries exceeded with url: // (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D62B00>, 'Connection to gpt.orence.net timed out. (connect timeout=10)'))\n",
      "Error checking website https://regex.ai/: HTTPSConnectionPool(host='regex.ai', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CC9A20>, 'Connection to regex.ai timed out. (connect timeout=10)'))\n",
      "Error checking website https://openprompt.co/: HTTPSConnectionPool(host='openprompt.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D555D0>, 'Connection to openprompt.co timed out. (connect timeout=10)'))\n",
      "Error checking website https://poe.com/: HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704E692D0>, 'Connection to poe.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://zhoubaotong.com/zh: HTTPSConnectionPool(host='zhoubaotong.com', port=443): Max retries exceeded with url: /zh (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704E696F0>, 'Connection to zhoubaotong.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://zcc.app/: HTTPSConnectionPool(host='zcc.app', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704E69450>, 'Connection to zcc.app timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.roomgpt.io/dream: HTTPSConnectionPool(host='www.roomgpt.io', port=443): Max retries exceeded with url: /dream (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040ABC70>, 'Connection to www.roomgpt.io timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.chatpdf.com/: HTTPSConnectionPool(host='www.chatpdf.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000287040C5480>, 'Connection to www.chatpdf.com timed out. (connect timeout=10)'))\n",
      "Error checking website https://hotoke.ai/: HTTPSConnectionPool(host='hotoke.ai', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704B88730>, 'Connection to hotoke.ai timed out. (connect timeout=10)'))\n",
      "Error checking website https://b.jimmylv.cn/: HTTPSConnectionPool(host='b.jimmylv.cn', port=443): Read timed out. (read timeout=10)\n",
      "Error checking website https://www.cursor.so/: HTTPSConnectionPool(host='www.cursor.so', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704CEF190>, 'Connection to www.cursor.so timed out. (connect timeout=10)'))\n",
      "Error checking website https://www.cursor.so/: HTTPSConnectionPool(host='www.cursor.so', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028704D62B60>, 'Connection to www.cursor.so timed out. (connect timeout=10)'))\n",
      "Error checking website https://open-gpt.app/: HTTPSConnectionPool(host='open-gpt.app', port=443): Read timed out. (read timeout=10)\n",
      "Done.\n"
     ]
    }
   ],
   "source": [
    "#解析文件，提取url信息\n",
    "import re\n",
    "import csv\n",
    "import requests\n",
    "import urllib3\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "\n",
    "urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)\n",
    "\n",
    "\n",
    "\n",
    "# 从csv文件中读取url列表\n",
    "url_list = []\n",
    "with open('./data/url_list.csv', 'r') as f:\n",
    "    for line in f.readlines():\n",
    "        url_list.append(line.strip())  # strip()方法是去除字符串第一个和最后一个字符的部分(默认为空格)\n",
    "# print(url_list)  # 打印 url_list 列表到控制台中(可以在你的程序中以\n",
    "\n",
    "\n",
    "def check_availability(url):\n",
    "    headers = {\n",
    "        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'\n",
    "    }\n",
    "\n",
    "    try:\n",
    "        response = requests.get(url, verify=False, headers=headers ,timeout=10)\n",
    "        if response.status_code == 200:\n",
    "            return (url, '可用')\n",
    "        else:\n",
    "            return (url, '不可用')\n",
    "    except Exception as e:\n",
    "        print(f'Error checking website {url}: {e}')\n",
    "        return (url, '不可用')\n",
    "\n",
    "availabe = []\n",
    "inavailable = []\n",
    "with ThreadPoolExecutor(max_workers=100) as executor:\n",
    "    futures = [executor.submit(check_availability, url) for url in url_list]\n",
    "    for future in futures:\n",
    "        result = future.result()\n",
    "        if result[1] == '可用':\n",
    "            availabe.append(result)\n",
    "        else:\n",
    "            inavailable.append(result)\n",
    "    # 保存available到文件csv中\n",
    "    with open('./data/available.csv', 'w', newline='') as f:\n",
    "        writer = csv.writer(f)\n",
    "        # writer.writerow(['URL', '状态'])\n",
    "        for i in availabe:\n",
    "            writer.writerow(i)\n",
    "    # 保存inavailable到文件csv中\n",
    "    with open('./data/inavailable.csv', 'w', newline='') as f:\n",
    "        writer = csv.writer(f)\n",
    "        writer.writerow(['URL', '状态'])\n",
    "        for i in inavailable:\n",
    "            writer.writerow(i)\n",
    "\n",
    "print(\"Done.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "mytorch",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
